antiquin/antiquin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('item/',include('item.urls')),
    path('cart/',include('cart.urls')),
    path('favourites/',include('favourites.urls')),
    path('account/',include('account.urls')),
    path('orders/',include('order.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

antiquin/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add_to_cart/<int:product_id>',views.add_to_cart, name='add_to_cart'),
    path('',views.view_cart, name="view_cart"),
    path('delete-item/<int:item_id>/',views.delete_item, name='delete_item'),
    path('update-cart/<int:product_id>/',views.update_cart, name='update_cart'),
    path('move-to-favourites/<int:product_id>',views.move_to_favourites, name='move_to_favourites')
]

antiquin/favourites/urls.py
from django.urls import path
from . import views

app_name = 'favourites'

urlpatterns = [
    path('add_to_favourites/<int:product_id>',views.add_to_favourites, name='add_to_favourites'),
    path('',views.view_favourites, name="favourites"),
    path('delete-item/<int:product_id>/',views.delete_item, name='delete_item'),
    path('move-to-cart/<int:product_id>/',views.move_to_cart, name='move_to_cart'),
]

antiquin/item/urls.py
from django.urls import path
from . import views

app_name = "item"

urlpatterns = [
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("search/", views.searchProduct, name="search"),
    path("new/", views.add_items, name="new"),
    path("edit/<int:pk>/", views.edit, name="edit"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("categories/", views.show_categories, name="category"),
    path("add-category", views.add_category, name="add_category"),
    path("delete-category/<int:pk>", views.delete_category, name="delete_category"),
]

antiquin/favourites/models.py
from django.db import models
from django.contrib.auth.models import User
from item.models import Product

# Create your models here.

class Favourite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}'s favorite: {self.product.name}"
    

antiquin/favourites/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from .models import Favourite
from item.models import Category
from cart.models import Cart, CartItem

@login_required
def add_to_favourites(request, product_id):
    product_id = int(product_id)
    user = request.user
    
    if not Favourite.objects.filter(user=user, product_id=product_id).exists():
        favourites = Favourite(user=user, product_id=product_id)
        favourites.save()

    return redirect('/favourites')

@login_required
def view_favourites(request):
    cart_items = None
    favourites = None
    
    if request.user.is_authenticated:
        user = request.user
        favourites = Favourite.objects.filter(user=user)
        fav_count = favourites.count()

        cart = Cart.objects.get(user=user)
        cart_items = CartItem.objects.filter(cart=cart)
        product_count = CartItem.objects.filter(cart=cart).count()
        total = sum(item.product.price * item.quantity for item in cart_items)
        categories = Category.objects.all()

    return render(request, 'favourites/favourites.html', {
        'favourites' : favourites,
        'fav_count' : fav_count,
        'product_count' : product_count,
        'total' : total,
        'categories' : categories
    })

@login_required
def delete_item(request, product_id):
    product = get_object_or_404(Favourite, id=product_id, user=request.user)
    product.delete()
    return redirect('/favourites')

@login_required
def move_to_cart(request, product_id):
    favourite = get_object_or_404(Favourite, product_id=product_id, user=request.user)

    cart, created = Cart.objects.get_or_create(user=request.user)
    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=favourite.product)

    favourite.delete()

    if not created:
        cart_item.quantity += 1
        cart_item.save()

    return redirect('/cart/')

antiquin/favourites/templates/favourites/favourites.html
{% extends "core/base.html" %}

{% block title %}Favourites{% endblock title %}

{% block content %}

<div class="container">
  <a class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover user-select-none" onclick="history.back()">
    <i class='bx bx-arrow-back pe-1'></i>
    Continue shopping
  </a>

    <h2 class="pt-4 pb-1">Favourites</h2>
    <hr>
    {% if favourites %}
    <div class="row">

        {% for favourite in favourites %}  
        <div class="col-lg-6 col-md-6">
          <div class="card mb-3">
            <div class="row p-3">
              <div class="col-4 col-lg-3 pb-3">
                <a href="{% url "item:detail" favourite.product.id %}">
                  <img src="{{ favourite.product.image.url }}" style="height: 7rem;" class="img-fluid ms-1 mt-2" />
                </a>  
              </div>
  
              <div class="col-6 col-lg-7 pt-2">
                <span>{{ favourite.product.name }}</span>
                <br>
                {% if favourite.product.description %}
                  <span class="text-secondary" style="font-size: .8rem;">{{ favourite.product.description }}</span>
                {% endif %}
                <br>
                <div>
                  Rs. {{ favourite.product.price }}
                </div>
                <div class="pt-2">
                  <a class="btn btn-warning" href="{% url "favourites:move_to_cart" favourite.product.id %}">Add to cart</a>
                </div>
              </div>
              <div class="col-2 col-lg-2 pt-2 ms-auto me-auto">
                <a 
                  class="bg-danger text-decoration-none text-white rounded p-0 ps-1 pe-1 fs-6"
                  onclick="location.href= '{% url "favourites:delete_item" favourite.id %}' "
                  style='cursor: pointer;'
                >&times;</a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      
    </div>
</div>
{% else %}
<p class="text-center text-body-tertiary pt-3">You haven't added any favorites yet.</p>
{% endif %}

{% endblock content %}