antiquin/antiquin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('item/',include('item.urls')),
    path('cart/',include('cart.urls')),
    path('favourites/',include('favourites.urls')),
    path('account/',include('account.urls')),
    path('orders/',include('order.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

antiquin/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add_to_cart/<int:product_id>',views.add_to_cart, name='add_to_cart'),
    path('',views.view_cart, name="view_cart"),
    path('delete-item/<int:item_id>/',views.delete_item, name='delete_item'),
    path('update-cart/<int:product_id>/',views.update_cart, name='update_cart'),
    path('move-to-favourites/<int:product_id>',views.move_to_favourites, name='move_to_favourites')
]

antiquin/item/urls.py
from django.urls import path
from . import views

app_name = "item"

urlpatterns = [
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("search/", views.searchProduct, name="search"),
    path("new/", views.add_items, name="new"),
    path("edit/<int:pk>/", views.edit, name="edit"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("categories/", views.show_categories, name="category"),
    path("add-category", views.add_category, name="add_category"),
    path("delete-category/<int:pk>", views.delete_category, name="delete_category"),
]

antiquin/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('checkout/',views.checkout, name='checkout'),
    path('start-order/',views.start_order, name='start_order'),
    path('cancel-order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('delete-order/<int:order_id>',views.delete_order, name='delete_order')
]

antiquin/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from item.models import Product

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    
    
class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.product.name} for {self.cart}'
    

antiquin/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required


from .models import Cart, CartItem, Product
from item.models import Category
from favourites.models import Favourite


@login_required
def add_to_cart(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    cart, created = Cart.objects.get_or_create(user=request.user)
    cart_item, created = CartItem.objects.get_or_create(
        cart=cart, product=product
        )

    if not created:
        cart_item.quantity += 1
        cart_item.save()

    return redirect('/cart/')

@login_required
def update_cart(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    
    cart = Cart.objects.get(user=request.user)
    
    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)

    if request.method == 'POST':
        action = request.POST.get('action')

        if action == 'add':
            cart_item.quantity += 1
        elif action == 'remove' and cart_item.quantity > 1:
            cart_item.quantity -= 1

        cart_item.save()

    return redirect('/cart/')


@login_required
def view_cart(request):
    cart_items = None
    favourites = None
    
    if request.user.is_authenticated:
        user = request.user

        cart, created = Cart.objects.get_or_create(user=user)
        
        cart_items = CartItem.objects.filter(cart=cart)
        product_count = CartItem.objects.filter(cart=cart).count()
        total = sum(item.product.price * item.quantity for item in cart_items)
        categories = Category.objects.all()
        product = Product.objects.all()

        for item in cart_items:
            item.subtotal = item.product.price * item.quantity

        favourites = Favourite.objects.filter(user=user)
        fav_count = favourites.count()

    return render(request, 'cart/view_cart.html', {
        'cart_items': cart_items,
        'total': total,
        'categories' : categories,
        'product' : product,
        'product_count' : product_count,
        'fav_count' : fav_count,
    })

@login_required
def delete_item(request, item_id):
    item = get_object_or_404(CartItem, id=item_id, cart__user=request.user)
    item.delete()
    return redirect('/cart/')

@login_required
def move_to_favourites(request, product_id):
    product_id = int(product_id)
    user = request.user

    cart, created = Cart.objects.get_or_create(user=user)

    cart_item = get_object_or_404(CartItem, cart=cart, product_id=product_id)
    cart_item.delete()

    if not Favourite.objects.filter(user=user, product_id=product_id).exists():
        favourite = Favourite(user=user, product_id=product_id)
        favourite.save()

    return redirect('/favourites')

antiquin/cart/templates/cart/cartItem.html
{% extends "core/base.html" %}

{% block title %}Cart{% endblock title %}

{% block content %}

<div class="container">
    
</div>

{% endblock content %}

antiquin/cart/templates/cart/view_cart.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}Cart{% endblock title %}

{% block content %}

<div class="container pb-5">
  <a class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover user-select-none" onclick="history.back()">
    <i class='bx bx-arrow-back pe-1'></i>
    Continue shopping
  </a>
  
  <h2 class="pt-4 pb-1">Your Cart</h2>
  <hr>
  {% if cart_items %}
    <div class="row cart-category">
      <div class="col-lg-5 col-md-5 col-sm-5 col-5">
        <h5>PRODUCT</h5>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-3">
        <h5>PRICE</h5>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-3 col-2">
        <h5>QUANTITY</h5>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-2">
        <h5>SUBTOTAL</h5>
      </div>
      <hr>
    </div>
    {% for item in cart_items %}
    <div class="row pb-3">  
      <div class="col-lg-1 col-md-1 col-sm-1 col-3">
        <a href="{% url "item:detail" item.product.id %}">
          <img src="{{ item.product.image.url }}" class="img-fluid" width="60rem"/>
        </a>
      </div>

      <div class="col-lg-4 col-md-4 col-sm-4 col-5">
        <div class="pt-2">{{ item.product.name }}</div>
        {% if item.product.description %}
          <span class="text-secondary" style="font-size: .8rem;">{{ item.product.description }}</span>
        {% endif %}
      </div>

      <div class="col-lg-2 col-md-2 col-sm-2 col-4 mt-4">
        ₹{{ item.product.price }}
      </div>

      <!-- ------------ quantity ---------- -->
      <div class="col-lg-3 col-md-3 col-sm-3 col-5 mt-4">
        <div class="d-flex">
          <form action="{% url 'cart:update_cart' item.product.id %}" method="post" class="d-flex">
            {% csrf_token %}
            <input type="hidden" name="action" value="remove">
            <button class="btn btn-outline-light text-dark border border-0 pb-0 pt-0 ps-1 pe-1 ms-1 me-1" type="submit">
              <i class='bx bxs-minus-circle'></i>
            </button>
          </form>
          
          <input  type="text" class="text-center form-control" value="{{ item.quantity }}" style="width: 2.9rem; height: 1.5rem;" readonly>
          <form action="{% url 'cart:update_cart' item.product.id %}" method="post" class="d-flex">
            {% csrf_token %}
            <input type="hidden" name="action" value="add">
            <button class="btn btn-outline-light text-dark border border-0 pt-0 pb-0 ps-1 pe-1 ms-1 me-1">
              <span><i class='bx bxs-plus-circle'></i></span>
            </button>
          </form>
        </div>
      </div>

      <!-- --------------- subtotal ------------------ -->
      <div class="col-lg-2 col-md-2 col-sm-2 col-6 mt-4">
        -{{ item.subtotal }}
        
        <a class="btn btn-light ps-1 pe-1 pb-1 p-0 ms-3" onclick="return confirmCancel()" href= "{% url "cart:delete_item" item.id %}">
          <img src="{% static "img/bin.png" %}" ></img>
        </a>
      </div>
    </div>
    <a href="{% url "cart:move_to_favourites" item.product.id %}" class="link-secondary link-offset-1 link-underline-opacity-50 link-underline-opacity-100-hover">
      Move to favourites
    </a>
    <hr>
    {% endfor %}

    <div class="hstack gap-2 fs-4 pb-4">
      <div class="p-2 me-auto">Total </div>
      <div class="vr" style="height: 2.5rem;"></div>
      <div class="p-2">₹{{ total }}</div>
    </div>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
      <button class="btn btn-dark rounded-0 ps-5 pe-5 p-2" 
        onclick="location.href= '{% url "order:checkout" %}' "
      >Checkout</button>
    </div>
</div>

{% else %}
<p class="text-center text-body-tertiary pt-3">Your cart is empty</p>
{% endif %}
{% endblock content %}