antiquin/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('',views.account,name='account'),
    path('edit/',views.edit_account, name='edit_account'),
    path('users/',views.users_page, name='users_page'),
    path('orders/',views.orders_page, name='orders_page'),
    path('orders-details/<int:pk>/',views.orders_details, name='orders_details'),
    path('order-delivered/<int:order_id>',views.deliver_order, name='deliver_order'),
    path('delivered/',views.delivered, name='delivered'), #delivered items to show for admin
    path('purchases/',views.delivered_customer, name='delivered_customer'), #purchase shows for user
    path('delete-user/<int:user_id>/',views.delete_user, name='delete_user'),
    path('order-details/<int:pk>',views.order_details,name='order_details')
]

antiquin/antiquin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('item/',include('item.urls')),
    path('cart/',include('cart.urls')),
    path('favourites/',include('favourites.urls')),
    path('account/',include('account.urls')),
    path('orders/',include('order.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

antiquin/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add_to_cart/<int:product_id>',views.add_to_cart, name='add_to_cart'),
    path('',views.view_cart, name="view_cart"),
    path('delete-item/<int:item_id>/',views.delete_item, name='delete_item'),
    path('update-cart/<int:product_id>/',views.update_cart, name='update_cart'),
    path('move-to-favourites/<int:product_id>',views.move_to_favourites, name='move_to_favourites')
]

antiquin/core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('',views.home, name='home'),
    path('sign-up/',views.sign_up, name='sign_up'),
    path('success/',views.success,name='success'),
    path('sign-in/',views.sign_in, name='sign-in'),
    path('sign-out',views.sign_out,name="sign-out"),
]

antiquin/favourites/urls.py
from django.urls import path
from . import views

app_name = 'favourites'

urlpatterns = [
    path('add_to_favourites/<int:product_id>',views.add_to_favourites, name='add_to_favourites'),
    path('',views.view_favourites, name="favourites"),
    path('delete-item/<int:product_id>/',views.delete_item, name='delete_item'),
    path('move-to-cart/<int:product_id>/',views.move_to_cart, name='move_to_cart'),
]

antiquin/item/urls.py
from django.urls import path
from . import views

app_name = "item"

urlpatterns = [
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("search/", views.searchProduct, name="search"),
    path("new/", views.add_items, name="new"),
    path("edit/<int:pk>/", views.edit, name="edit"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("categories/", views.show_categories, name="category"),
    path("add-category", views.add_category, name="add_category"),
    path("delete-category/<int:pk>", views.delete_category, name="delete_category"),
]

antiquin/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = {'username', 'email', 'password1', 'password2'}

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'form-control mb-3',
        'id': 'username',
        'aria-describedby':"inputGroup-sizing-sm",
        'autofocus' : True
    }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Email',
        'class' : 'form-control mb-3',
        'id' : 'email',
        'aria-describedby':"inputGroup-sizing-sm"
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class' : 'form-control mb-3',
        'id' : 'password1',
        'aria-describedby':"inputGroup-sizing-sm"
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm password',
        'class' : 'form-control',
        'id' : 'password2',
        'aria-describedby':"inputGroup-sizing-sm"
    }))


class LoginForm(AuthenticationForm):
     username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'form-control mb-4',
        'id': 'username',
        'autofocus' : True
    }))
     password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class' : 'form-control mb-3',
        'id' : 'password1'
    }))

antiquin/core/views.py
from django import forms
from django.shortcuts import render, redirect
from django.contrib.auth import logout, login, authenticate
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages


from item.models import Category, Product
from cart.models import Cart, CartItem
from favourites.models import Favourite
from .forms import SignupForm, LoginForm


def home(request):
    cart_items = None
    favourites = None
    categories = Category.objects.all()
    products = Product.objects.filter(is_sold=False)

    items_per_page = 12

    paginator = Paginator(products, items_per_page)

    page = request.GET.get('page')

    try:
        paginated_products = paginator.page(page)
    except PageNotAnInteger:
        paginated_products = paginator.page(1)
    except EmptyPage:
        paginated_products = paginator.page(paginator.num_pages)

    # cart total, count and favourite count
    if request.user.is_authenticated:
        user = request.user

        user_cart, created = Cart.objects.get_or_create(user=user)
        
        cart_items = CartItem.objects.filter(cart=user_cart)
        product_count = cart_items.count()
        total = sum(item.product.price * item.quantity for item in cart_items)

        favourites = Favourite.objects.filter(user=user)
        fav_count = favourites.count()

        return render(request, 'core/index.html', {
            'categories': categories,
            # here products need not to be called
            'products': paginated_products,
            'total': total,
            'product_count': product_count,
            'fav_count': fav_count,
        })

    return render(request, 'core/index.html',{
        'categories' : categories,
        'products' : paginated_products
    })


def sign_up(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        
        if form.is_valid():
            user = form.save()
            return redirect('/success/')
    else:
        form = SignupForm()
    return render(request, 'core/signup.html', {'form' : form})


def sign_in(request):
    if request.method == 'POST':
        form = LoginForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                next_url = request.GET.get('next', reverse('home'))
                return HttpResponseRedirect(next_url)
    else:
        form = LoginForm()

    return render(request, 'core/login.html', {
        'form' : form
    })


def success(request):
    return render(request, 'core/success.html')

def sign_out(request):
    logout(request)
    return redirect('sign-in')

antiquin/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <!-- google icons -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
    />
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap"
      rel="stylesheet">
    <!-- boxicons -->
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
    <!-- font-awesome cdn -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
    />
    <!-- css file -->
    <link rel="stylesheet" href="{% static "css\style.css" %}">
    <title>{% block title %}{% endblock title %} | AntiQuin</title>
  </head>
  <body>
    <nav class="navbar fixed-top bg-white pt-0 pb-0 border-bottom border-2">
      <div class="container pt-2">
        <a href="{% url "home" %}">
          <img src="{% static "img\logo.png" %}" alt="logo" class="logo" />
        </a>
        <div class="search-bar pt-3 ms-auto">
          <!-- search filter -->
            <ul class="search-bar-list rounded">
              <li class="dropdown mt-2 pt-1 ms-2" id="categoryDropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Categories
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url "home" %}">All categories</a></li>
                    {% for category in categories %}
                    <li>
                        <a class="dropdown-item category-link" href="#" data-category="{{ category.name }}">
                            {{ category.name }}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
              </li>            

              <li class="me-auto mt-auto">
                <div>
                  <form
                    method="post"
                    class="d-flex ms-2 mt-auto"
                    action="{% url 'item:search' %}">
                      {% csrf_token %}              
                    <input
                      class="form-control search-option"
                      placeholder="I'm searching for..."
                      name='searched'
                      value="{{ searched }}"
                    />
                    <button 
                      class='search-submit-btn ms-3'
                      type="submit"
                      ><span class="material-symbols-outlined text-secondary"
                        >search</span
                      ></button
                    >
                  </form>
                </div>
              </li>
            </ul>
        </div>

        <div class="main-user-cart-div ms-auto">
          <!-- user panel  -->
          <div class="user-panel-div pt-3">
            <ul class="user-panel">
              <li class="pe-3">
                {% if user.is_authenticated %}
                <a href="{% url "account:account" %}"
                  ><span class="material-symbols-outlined">
                    account_circle
                  </span></a
                >
                {% else %}
                <a href="{% url "sign-in" %}?next={% url "account:account" %}"
                  ><span class="material-symbols-outlined">
                    account_circle
                  </span></a
                >
                {% endif %}
              </li>
              <li class="pe-3">
                <a 
                  href="
                    {% if user.is_authenticated %}{% url 'favourites:favourites' %}
                    {% else %}
                    {% url 'sign-in' %}?next={% url 'favourites:favourites' %}{% endif %}"
                  class="position-relative"
                ><span class="material-symbols-outlined"> favorite </span>
                  <!-- work on backend -------------------------- -->
                  <span
                    class="position-absolute bottom-50 ps-1 pe-1 translate-middle badge rounded-pill bg-warning"
                  >
                  {% if fav_count and request.user.username %}
                  {{ fav_count }}
                  {% else %}
                  0
                  {% endif %}
                  </span>
                </a>
              </li>

              <!-- view cart ------------------- -->
              
              <li>
                <a 
                  href="{% if user.is_authenticated %}{% url 'cart:view_cart' %}
                  {% else %}{% url 'sign-in' %}?next={% url 'cart:view_cart' %}
                  {% endif %}"
                  class="position-relative"
                >
                  <span class="shopping-bag">
                    <i class='bx bx-shopping-bag'></i>
                  </span>

                  <span 
                    class="position-absolute bottom-50 ps-1 pe-1 pb-1 translate-middle badge rounded-pill bg-warning">
                    {% if product_count and request.user.username %}
                    {{ product_count }}
                    {% else %}
                    0
                    {% endif %}
                  </span>
                </a>
              </li>
            </ul>
          </div>

          <!-- cart total -->
          <div class="div-cart pt-3">
            <ul>
              <li>
                <span class="badge text-dark bg-dark-subtle text-wrap">
                  Your Cart
                </span>
              </li>
              <!-- ----------------------------cart total------------------ -->
              <li>
                {% if total and request.user.username %}
                  <span>₹{{ total }}</span>
                {% else %}
                  <span>₹000.00</span>
                {% endif %}
              </li>
            </ul>
          </div>
        </div>
        
        <!-- ----------------- menu icon  -------------------------- -->

        <button class="navbar-toggler offcanvas-btn" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
          <div class="offcanvas-header">
            <a href="{% url "home" %}" class="text-decoration-none">
              <h2 class="offcanvas-title text-black bg-warning ps-1 pe-1" id="offcanvasNavbarLabel">ANTIQUIN</h2>
            </a>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          
          </div>
          
          <div class="offcanvas-body">
            <div class='responsive-menu-bar'>
              <ul class="ps-0">
                <li class="pb-3">
                  <a href="{% url "account:account" %}" class="text-decoration-none text-dark">
                    <img src="{% static "img/user-circle.png" %}" alt="" width="40rem">
                    <span class="ps-5 pe-5">Profile</span>
                  </a>
                </li>

                <li class="pb-3">
                  <a href="{% if user.is_authenticated %}{% url 'favourites:favourites' %}
                    {% else %}
                    {% url 'sign-in' %}?next={% url 'favourites:favourites' %}{% endif %}" 
                    class="text-decoration-none text-dark">
                    <img src="{% static "img/heart.png" %}" alt="" width="40rem">
                    <span class="ps-5 pe-5">Your Favourites</span>
                  </a>
                </li>

                <!-- view cart ------------------- -->
                <li class="pb-3">
                  <a href="{% if user.is_authenticated %}{% url 'cart:view_cart' %}
                    {% else %}{% url 'sign-in' %}?next={% url 'cart:view_cart' %}
                    {% endif %}" class="text-decoration-none text-dark">
                    <img src="{% static "img/shopping-bag.png" %}" alt="" width="40rem">
                    <span class="ps-5 pe-5">Your Cart</span>
                  </a>
                </li>

                <li class="mt-5 text-center">
                  <span class="badge text-dark bg-dark-subtle text-wrap fs-5">
                    Cart Total : 
                  </span>
                </li>
                <!-- ----------------------------cart total------------------ -->
                <li class="text-center fs-6">
                  {% if total and request.user.username %}
                    <span>₹{{ total }}</span>
                  {% else %}
                    <span>₹000.00</span>
                  {% endif %}
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <div style="margin-top: 8rem;">
      {% block content %}{% endblock content %}
    </div>
  
    <script src="{% static "js\script.js" %}"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
      integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

antiquin/core/templates/core/index.html
{% extends "core/base.html" %}
{% load static %}
<title>
  {% block title %}
    Home
  {% endblock title %}
</title>
{% block content %}
  <!-- Products -->
  <div class="container pt-4">
    <h2 class="pb-2">Featured Products</h2>
    <div class="row">
      {% for product in products %}
        <!-- loop starts here.... -->
        <div class="col-lg-3 col-md-4 col-sm-6 pt-3 pb-3 product-item category-{{ product.category.name }}">
          <div class="card product-div ">
            <a class="product-img-link" href="{% url "item:detail" product.id %}">
              <div class="card-img">
                {% if product.image %}
                  <img src="{{ product.image.url }}"
                       class="img-fluid item-img object-fit-cover" />
                {% else %}
                  <img src="#" alt="image of {{ product.name }}" class="img-fluid item-img" />
                {% endif %}
              </div>
            </a>
            <div class="card-body">
              <div class="text-dark fs-6 lh-1 fw-bold">{{ product.name }}</div>
              <div class="fs-6 text-body-tertiary fw-light pb-2">Price: ₹{{ product.price }}</div>
              <!-- -------------------- add to cart btn ------------------ -->
              <div class="d-grid gap-2">
                <button class="btn btn-warning"
                        {% if user.is_authenticated %} onclick="location.href = '{% url "cart:add_to_cart" product.id %}' " {% else %} onclick="location.href = '{% url 'sign-in' %}?next={% url "cart:add_to_cart" product.id %}' " {% endif %}>
                  Add to cart
                </button>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    <!-- fixed social media icon -->
    <div class="ms-auto social-media-div">
      <a href="http://wa.me/918606923166" class="social-media-link">
        <i class="bx bxl-whatsapp social-media"></i>
      </a>
    </div>
    <div class="text-center pb-3">
      <span class="step-links">
        <span class="current">Page {{ products.number }} of {{ products.paginator.num_pages }}.</span>
        <br>
        {% if products.has_previous %}
          <a href="?page=1" class="text-dark">&laquo; First</a>
          -
          <a href="?page={{ products.previous_page_number }}" class="text-dark">&laquo; Previous</a>
          {% if products.has_next %}-{% endif %}
        {% endif %}
        {% if products.has_next %}
          <a href="?page={{ products.next_page_number }}" class="text-dark">Next &raquo;</a>
          -
          <a href="?page={{ products.paginator.num_pages }}" class="text-dark">Last &raquo;</a>
        {% endif %}
      </span>
    </div>
  </div>
{% endblock content %}

antiquin/core/templates/core/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <!-- google icons -->
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap"
      rel="stylesheet"
    />
    <!-- google fonts -->
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap"
      rel="stylesheet"
    />
    <!-- boxicons -->
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
    <!-- css file -->
    <link rel="stylesheet" href="{% static "css\style.css" %}">
    <title>Sign in</title>
  </head>
  <body>

    <div class="container-fluid">
      <div class="position-relative">
        <div class="position-absolute top-0 start-0 mt-4 ms-3">
          <button
              onclick="location.href = '{% url "home" %}' " 
             class='text-dark search-submit-btn pe-2'
          >
            <i class='bx bxs-home'></i>
            Home
          </button>
          |
          <button 
            onclick="history.back()"
            class="text-dark search-submit-btn rounded ps-2">
            <i class='bx bx-arrow-back'></i>
            Back
          </button>
        </div>
      </div>
    </div>

    <div class="container pt-5">
      <div class="container signup-form">
        <h1 class="text-center text-dark">
          Welcome back!
        </h1>
        <p class="text text-center pb-3 pt-1">
          <a class="bg-warning text-dark text-decoration-none ps-2 pe-2 fs-6"
             href="{% url "home" %}"
             title="Home"
            >AntiQuin</a
          >
        </p>
          <form 
            action="{% if request.GET.next %}{% url 'sign-in' %}?next={{ request.GET.next }}
            {% else %}{% url 'sign-in' %}{% endif %}" 
            method="post"
          >
          {% csrf_token %} {{ form.username }} {{ form.password }}

          <div class="mt-3">
            {% if form.errors %}
              <p class="text-danger rounded p-2 bg-danger-subtle lh-sm" 
                style="font-size: .8rem ;">
                  
                {% for field in form %}
                  {% for error in field.errors %}
                  <span>{{ error|escape }}</span>
                  <br>
                  {% endfor %}
                {% endfor %}

                  {% for error in form.non_field_errors %}
                    <span>{{ error|escape }}</span>
                  {% endfor %}
              </p>
            {% endif %}
         </div>
          <div class="text-center pb-4">
            <button class="btn btn-dark" type="submit">Sign in</button>
          </div>
          <p class='text-center'> Don't have an account? 
            <br>
            <a href="{% url "sign_up" %}"> Create an account</a>
          </p>
        </form>
      </div>
    </div>
  </body>
</html>

antiquin/core/templates/core/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <!-- google icons -->
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap"
      rel="stylesheet"
    />
    <!-- google fonts -->
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap"
      rel="stylesheet"
    />
    <!-- boxicons -->
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
    <!-- css file -->
    <link rel="stylesheet" href="{% static "css\style.css" %}">
    <title>Create an account</title>
  </head>
  <body>

    <div class="container-fluid">
      <div class="position-relative">
        <div class="position-absolute top-0 start-0 mt-4 ms-3">
          <a href="{% url "home" %}"
             class='text-dark text-decoration-none pe-2'
          >
            <i class='bx bxs-home' ></i>
            Home
          </a>
        </div>
      </div>
    </div>

    <div class="container pt-5">
      <div class="container signup-form">
        <h1 class="text-center text-dark pb-4">Create an account</h1>
        
        <div>
          <form action="." method="post">
            {% csrf_token %}

            {{ form.username }}
            {{ form.email }}
            {{ form.password1 }}
            {{ form.password2 }}
            
            <div class="mt-3">
               {% if form.errors %}
              <p class="text-danger fw-light rounded p-2 bg-danger-subtle lh-sm" 
                style="font-size: .9rem ;">
                 
                {% for field in form %}
                  {% for error in field.errors %}
                  <span>{{ error }}</span>
                  <br>
                  {% endfor %}
                {% endfor %}

                {% for error in form.non_field_errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </p>
            {% endif %}
            </div>
           
            <div class="text-center pb-3">
              <button class="btn btn-dark mt-2" type="submit">Create an account</button>
            </div>
            <p class="text-center">
              Already have an account?
              <br>
              <a href="{% url "sign-in" %}">Sign in</a>
            </p> 
          </form>
        </div>
      </div>
    </div>
  </body>
</html>

antiquin/core/templates/core/success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <!-- google icons -->
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap"
      rel="stylesheet"
    />
    <!-- google fonts -->
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap"
      rel="stylesheet"
    />
    <!-- boxicons -->
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
    <!-- css file -->
    <link rel="stylesheet" href="{% static "css\style.css" %}">
    <title>Account Created!</title>
  </head>
  <body>
    <div class="container mt-5">
      <div class="position-absolute top-50 start-50 translate-middle">
        <div class="text-success text-center">
          <div class="pb-3" style="font-size: 2rem">
            <i class='bx bxs-badge-check bx-burst-hover'></i>
          </div>

          <h5 class="pb-4">Account Created Successfully!</h5>
  
          <p>
            <a 
              href="{% url 'sign-in' %}" 
              class="link-dark link-offset-2 link-underline-opacity-50 link-underline-opacity-100-hover"
            >
            Sign in
            </a>
          </p>
        </div>
      </div>
    </div>
  </body>
</html>