antiquin/antiquin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('item/',include('item.urls')),
    path('cart/',include('cart.urls')),
    path('favourites/',include('favourites.urls')),
    path('account/',include('account.urls')),
    path('orders/',include('order.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

antiquin/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add_to_cart/<int:product_id>',views.add_to_cart, name='add_to_cart'),
    path('',views.view_cart, name="view_cart"),
    path('delete-item/<int:item_id>/',views.delete_item, name='delete_item'),
    path('update-cart/<int:product_id>/',views.update_cart, name='update_cart'),
    path('move-to-favourites/<int:product_id>',views.move_to_favourites, name='move_to_favourites')
]

antiquin/favourites/urls.py
from django.urls import path
from . import views

app_name = 'favourites'

urlpatterns = [
    path('add_to_favourites/<int:product_id>',views.add_to_favourites, name='add_to_favourites'),
    path('',views.view_favourites, name="favourites"),
    path('delete-item/<int:product_id>/',views.delete_item, name='delete_item'),
    path('move-to-cart/<int:product_id>/',views.move_to_cart, name='move_to_cart'),
]

antiquin/item/urls.py
from django.urls import path
from . import views

app_name = "item"

urlpatterns = [
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("search/", views.searchProduct, name="search"),
    path("new/", views.add_items, name="new"),
    path("edit/<int:pk>/", views.edit, name="edit"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("categories/", views.show_categories, name="category"),
    path("add-category", views.add_category, name="add_category"),
    path("delete-category/<int:pk>", views.delete_category, name="delete_category"),
]

antiquin/item/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name="items", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    is_sold = models.BooleanField(default=False)
    quantity = models.PositiveIntegerField(default=1)
    created_by = models.ForeignKey(User, related_name="items", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Products"
        ordering = ("created_at",)

    def __str__(self):
        return self.name

antiquin/item/forms.py
from django import forms

from .models import Product, Category

INPUT_CLASSES = "form-control"


class NewProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ("category", "name", "description", "price", "image")

        widgets = {
            "category": forms.Select(attrs={"class": INPUT_CLASSES}),
            "name": forms.TextInput(attrs={"class": INPUT_CLASSES}),
            "description": forms.TextInput(attrs={"class": INPUT_CLASSES}),
            "price": forms.NumberInput(attrs={"class": INPUT_CLASSES}),
            "image": forms.FileInput(attrs={"class": INPUT_CLASSES}),
        }


class EditProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            "category", "name", "description", "price", "image", "is_sold"
        )

        widgets = {
            "category": forms.Select(attrs={"class": INPUT_CLASSES}),
            "name": forms.TextInput(attrs={"class": INPUT_CLASSES}),
            "description": forms.TextInput(attrs={"class": INPUT_CLASSES}),
            "price": forms.NumberInput(attrs={"class": INPUT_CLASSES}),
            "image": forms.FileInput(attrs={"class": INPUT_CLASSES}),
            "is_sold": forms.CheckboxInput(
                attrs={"class": "form-check-input ms-2 text-black"}
            ),
        }


class NewCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ("name",)
        widgets = {
            "name": forms.TextInput(attrs={"class": INPUT_CLASSES}),
        }

antiquin/item/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from item.models import Category, Product
from cart.models import CartItem, Cart
from favourites.models import Favourite
from .forms import NewProductForm, EditProductForm, NewCategoryForm


def get_user_data(request):
    user_data = {
        "user": None,
        "cart_items": None,
        "total": None,
        "product_count": None,
        "fav_count": None,
    }

    if request.user.is_authenticated:
        user_data["user"] = request.user
        cart = Cart.objects.get(user=user_data["user"])
        user_data["cart_items"] = CartItem.objects.filter(cart=cart)
        user_data["product_count"] = user_data["cart_items"].count()
        user_data["total"] = sum(
            item.product.price * item.quantity for item in user_data["cart_items"]
        )
        user_data["fav_count"] = Favourite.objects.filter(
            user=user_data["user"]
        ).count()

    return user_data


def detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    categories = Category.objects.all()
    related_items = Product.objects.filter(
        category=product.category, is_sold=False
    ).exclude(pk=pk)[0:4]

    user_data = get_user_data(request)

    return render(
        request,
        "item/details.html",
        {
            "product": product,
            "categories": categories,
            "related_items": related_items,
            **user_data,
        },
    )


def searchProduct(request):
    searched = None
    products = None
    categories = Category.objects.all()

    if request.method == "POST":
        searched = request.POST.get("searched", "")
        products = Product.objects.filter(
            Q(name__contains=searched) | Q(description__contains=searched)
        )

    user_data = get_user_data(request)

    return render(
        request,
        "item/searchProducts.html",
        {
            "searched": searched,
            "products": products,
            "categories": categories,
            **user_data,
        },
    )


# Account section -- staff only logic --
@login_required
def add_items(request):
    user_data = get_user_data(request)
    categories = Category.objects.all()
    if request.method == "POST":
        form = NewProductForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect("item:detail", pk=item.id)

    else:
        form = NewProductForm()

    return render(
        request,
        "item/form.html",
        {
            "form": form, "title": "Add Item",
            "categories": categories, **user_data
        },
    )


@login_required
def edit(request, pk):
    categories = Category.objects.all()
    item = get_object_or_404(Product, pk=pk, created_by=request.user)
    user_data = {
        "user": None,
        "cart_items": None,
        "total": None,
        "product_count": None,
        "fav_count": None,
    }

    if request.user.is_authenticated:
        user_data["user"] = request.user
        cart = Cart.objects.get(user=user_data["user"])
        user_data["cart_items"] = CartItem.objects.filter(cart=cart)
        user_data["product_count"] = user_data["cart_items"].count()
        user_data["total"] = sum(
            item.product.price * item.quantity for item in user_data["cart_items"]
        )
        user_data["fav_count"] = Favourite.objects.filter(
            user=user_data["user"]
        ).count()

    if request.method == "POST":
        form = EditProductForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect("item:detail", pk=item.id)
    else:
        form = EditProductForm(instance=item)

    return render(
        request,
        "item/form.html",
        {"form": form, "title": "Edit Item", 
         "categories": categories, **user_data},
    )


@login_required
def delete(request, pk):
    item = get_object_or_404(Product, pk=pk, created_by=request.user)
    item.delete()

    return redirect("/")


@login_required
def show_categories(request):
    categories = Category.objects.all()
    return render(
        request, "account/categories.html", 
        {"categories": categories}
    )


@login_required
def add_category(request):
    if request.method == "POST":
        form = NewCategoryForm(request.POST)

        if form.is_valid():
            category = form.save()

            return redirect("item:category")
    else:
        form = NewCategoryForm()
    return render(request, "account/add_category.html", {
        "form": form, "category": category,
        })


@login_required
def delete_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    category.delete()
    return redirect("/item/categories")

antiquin/item/templates/item/details.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}
  {{ product.name }}
{% endblock title %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-7 col-md-7 col-sm-12 mb-4">
        <div>
          {% if product.image %}
            <a target="_blank" href="{{ product.image.url }}">
              <img src="{{ product.image.url }}"
                   width="350rem"
                   alt="..."
                   class="img-fluid rounded mx-auto d-block" />
            </a>
          {% else %}
            <img src="#"
                 alt="image of {{ product.name }}"
                 class="img-fluid item-img object-fit-none" />
            <h1 class="text-center p-5">Image not Available</h1>
          {% endif %}
        </div>
      </div>
      <div class="col-lg-5 col-md-5 col-sm-12">
        <div class="card border-1 border-warning position-relative p-3  mt-2">
          <div>
            <a {% if user.is_authenticated %} href="{% url "favourites:add_to_favourites" product.id %}" {% else %} href="{% url 'sign-in' %}?next={% url "favourites:add_to_favourites" product.id %}" {% endif %}
               class="btn-add-to-favourite text-danger fs-1 position-absolute top-0 end-0 mt-1 pt-1 me-3">
              <i class="bx bxs-heart"></i>
            </a>
          </div>
          <h5 class="card-title">{{ product.name }}</h5>
          {% if product.description %}<h5 class="text-dark" style="font-size: .9rem;">{{ product.description }}</h5>{% endif %}
          <div class="card-text text-body-tertiary">MRP inclusive of all taxes</div>
          <p class="card-text">Rs. {{ product.price }}</p>
          {% if user.is_staff %}
            <div class="container">
              <div class="row p-3 bg-body-tertiary rounded ms-auto me-auto">
                <p>You can work with your products!</p>
                <div class="col-6">
                  <a class="btn btn-outline-danger"
                     onclick="return confirmCancel()"
                     href="{% url "item:delete" product.id %}">Delete</a>
                </div>
                <div class="col-6">
                  <button class="btn btn-outline-dark ps-4 pe-4"
                          onclick="location.href = '{% url "item:edit" product.id %}' ">Edit</button>
                </div>
              </div>
            </div>
          {% else %}
            <p class="text-black-50 mt-5">
              <i class="bx bx-info-circle"></i>
              Delivery Time : 2-7 Days
              <br>
              <svg xmlns="http://www.w3.org/2000/svg"
                   height="24px"
                   viewBox="0 -960 960 960"
                   width="24px"
                   fill="#a9a9a9">
                <path d="M240-160q-50 0-85-35t-35-85H40v-440q0-33 23.5-56.5T120-800h560v160h120l120 160v200h-80q0 50-35 85t-85 35q-50 0-85-35t-35-85H360q0 50-35 85t-85 35Zm0-80q17 0 28.5-11.5T280-280q0-17-11.5-28.5T240-320q-17 0-28.5 11.5T200-280q0 17 11.5 28.5T240-240ZM120-360h32q17-18 39-29t49-11q27 0 49 11t39 29h272v-360H120v360Zm600 120q17 0 28.5-11.5T760-280q0-17-11.5-28.5T720-320q-17 0-28.5 11.5T680-280q0 17 11.5 28.5T720-240Zm-40-200h170l-90-120h-80v120ZM360-540Z" />
              </svg>
              FREE Delivery
            </p>
            <button class="btn btn-warning fs-6"
                    {% if user.is_authenticated %} onclick="location.href = '{% url "cart:add_to_cart" product.id %}' " {% else %} onclick="location.href = '{% url 'sign-in' %}?next={% url "cart:add_to_cart" product.id %}' " {% endif %}>
              Add
              <i class="bx bx-shopping-bag fw-medium"></i>
            </button>
          {% endif %}
        </div>
      </div>
    </div>
    {% if related_items %}
      <div class="container pt-5">
        <h2>Related Products</h2>
        <hr>
        <div class="row">
          {% for item in related_items %}
            <div class="col-lg-3 col-md-4 col-sm-6 pt-3 pb-3">
              <div class="card product-div">
                <a class="product-img-link" href="{% url "item:detail" item.id %}">
                  <div class="card-img">
                    {% if item.image %}
                      <img src="{{ item.image.url }}"
                           class="img-fluid item-img object-fit-cover"
                           alt="..." />
                    {% else %}
                      <img src="#"
                           alt="image of {{ product.name }}"
                           class="img-fluid item-img object-fit-cover" />
                    {% endif %}
                  </div>
                </a>
                <div class="card-body">
                  <div class="text-dark fs-6 lh-1 fw-bold">{{ item.name }}</div>
                  <div class="fs-6 text-body-tertiary fw-light pb-2">Price: ₹{{ item.price }}</div>
                  <div class="d-grid gap-2">
                    <button class="btn btn-warning"
                            onclick="location.href ='{% url "item:detail" item.id %}' ">View</button>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    {% endif %}
  </div>
{% endblock content %}

antiquin/item/templates/item/form.html
{% extends "core/base.html" %}
{% block title %}
    {{ title }}
{% endblock title %}
{% block content %}
    <div class="container pb-3">
        <h1 class="mb-3">{{ title }}</h1>
        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-6 col-12">{{ form.as_p }}</div>
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="text-danger-emphasis fs-6 lh-sm">
                    {% for field in form %}{{ field.errors }}{% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <button type="submit" class="btn btn-dark">Submit</button>
        </form>
    </div>
{% endblock content %}

antiquin/item/templates/item/searchProducts.html
{% extends "core/base.html" %}
{% block title %}
    Search
{% endblock title %}
{% block content %}
    {% if searched %}
        <h1 class="text-center text-dark pt-3">
            Showing results for <span class="text-warning">' {{ searched }} '</span>
        </h1>
        <hr style="width: 15rem;
                   height: .1rem;
                   background-color: yellow;
                   color: yellow;
                   margin: auto" />
        <div class="container pt-4">
            <div class="row">
                {% for product in products %}
                    <!-- loop starts here.... -->
                    <div class="col-lg-3 col-md-4 col-sm-6 pt-3 pb-3">
                        <div class="card product-div">
                            <a class="product-img-link" href="{% url "item:detail" product.id %}">
                                <div class="card-img">
                                    {% if product.image %}
                                        <img src="{{ product.image.url }}"
                                             alt="image of {{ product.item }}"
                                             class="img-fluid object-fit-cover item-img" />
                                    {% else %}
                                        <img src="#" alt="image of {{ product.name }}" class="img-fluid item-img" />
                                    {% endif %}
                                </div>
                            </a>
                            <div class="card-body">
                                <div class="text-dark fs-6 lh-1 fw-bold">{{ product.name }}</div>
                                <div class="fs-6 text-body-tertiary fw-light pb-2">Price: ₹{{ product.price }}</div>
                                <div class="d-grid gap-2">
                                    <button class="btn btn-warning"
                                            onclick="location.href = '{% url "cart:add_to_cart" product.id %}' ">
                                        Add to cart
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <h1 class="text-center text-dark pt-3">Please enter a prompt...</h1>
    {% endif %}
{% endblock content %}